puddle/conversation/urls.py
from django.urls import path

from .views import *


app_name = 'conversation'

urlpatterns = [
    path('', inbox, name='inbox'),
    path('new/<int:item_pk>/', new_conversation, name='new'),
    path('<int:pk>/', detail, name='detail'),
]

puddle/core/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('sign_up/', SignUpUser.as_view(), name='sign_up'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

puddle/dashboard/urls.py
from django.urls import path

from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', DashboardHome.as_view(), name='index'),
]

puddle/item/urls.py
from django.urls import path

from .views import *


app_name = 'item'

urlpatterns = [
    path('', items, name='items'),
    path('<int:pk>/', ItemDetail.as_view(), name='detail'),
    path('new/', CreateItem.as_view(), name='new'),
    path('<int:pk>/delete/', delete_item, name='delete'),
    path('<int:pk>/edit/', EditItem.as_view(), name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.urls import path, include
from core.views import *
from item.views import *


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    # get rid of the last line
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpUserForm(UserCreationForm):
    """User registration form"""
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'John'}),
            'email': forms.EmailInput(attrs={'required': True, 'placeholder': 'JohnWick23@gmail.com'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Your password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Repeat your password'})
        }


class LoginUserForm(AuthenticationForm):
    """User login form"""
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'placeholder': 'John'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Your password'}))

puddle/core/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.db.models import Count

from core.forms import SignUpUserForm, LoginUserForm
from item.models import Category, Item


def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all().annotate(total=Count('items'))

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })


def contact(request):
    return render(request, 'core/contact.html')


class SignUpUser(CreateView):
    """User registration"""
    form_class = SignUpUserForm
    template_name = 'core/sign_up.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        user = form.save()
        # login(self.request, user)
        return redirect('/login/')


class LoginUser(LoginView):
    """Login user"""
    form_class = LoginUserForm
    template_name = 'core/login.html'
    success_url = 'index/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def logout_user(request):
    logout(request)
    return redirect('/')

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content='width=device-width, initial-scale=1.0'>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Puddle</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'core:index' %}" class="text-4xl font-semibold">Puddle</a>
        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}"
               class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>
            <p class="inline ml-2 text-3xl font-semibold">|</p>
            <p class="inline text-lg font-semibold">Greetings, {{ user.username }}</p>
            <a href="{% url 'core:logout' %}"
               class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out
            </a>
            {% else %}
            <a href="{% url 'core:sign_up' %}"
               class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up
            </a>
            <a href="{% url 'core:login' %}"
               class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in
            </a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
      {% block content %}
      {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Some information about this project</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="txt-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="txt-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="txt-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="txt-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>The contact page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <!--    item:detail uses app_name (item) and the name (detail in item/urls.py) -->
                    {% if item.image.url is not None %}
                    <div><img src="{{ item.image.url }}" class="rounded-t-xl"></div>
                    {% else %}
                    <div class="rounded-t-xl">No image</div>
                    {% endif %}
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="{% url 'item:items'%}?category={{ category.id }}">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">items: {{ category.total }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-2/3 mx-auto p-5 bg-gray-100 rounded-xl">
    <p class="text-2xl">Log in</p>
    <div class="text-red-600 mt-5">{{ form.non_field_errors }}</div>
    <form class="mt-10" method="post">
        {% csrf_token %}
        <div class="grid gap-6 mb-6 md-3">
            {% for f in form %}
            <div>
                <label class="block mb-2 text-lg font-semibold" for="{{ f.id_for_label }}">{{f.label}}</label>
                <div class="text-red-600 mb-5">{{ f.errors }}</div>
                {{ f|add_class:"border border-gray-300 text-gray-900 text-lg rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" }}
            </div>
            {% endfor %}
            <button type="submit" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log in</button>
        </div>
    </form>
</div>
{% endblock %}

puddle/core/templates/core/sign_up.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-2/3 mx-auto p-5 bg-gray-100 rounded-xl">
    <p class="text-2xl">Sign up</p>
    <div class="text-red-600 mt-5">{{ form.non_field_errors }}</div>
    <form class="mt-10" method="post">
        {% csrf_token %}
        <div class="grid gap-6 mb-6 md-3">
            {% for f in form %}
            <div>
                <label class="block mb-2 text-lg font-semibold" for="{{ f.id_for_label }}">{{f.label}}</label>
                <div class="text-red-600 mb-5">{{f.errors}}</div>
                {{ f|add_class:"border border-gray-300 text-gray-900 text-lg rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" }}
                </div>
            {% endfor %}
            <button type="submit" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</button>
        </div>
    </form>
</div>

{% endblock %}