puddle/conversation/urls.py
from django.urls import path

from .views import *


app_name = 'conversation'

urlpatterns = [
    path('', inbox, name='inbox'),
    path('new/<int:item_pk>/', new_conversation, name='new'),
    path('<int:pk>/', detail, name='detail'),
]

puddle/core/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('sign_up/', SignUpUser.as_view(), name='sign_up'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

puddle/item/urls.py
from django.urls import path

from .views import *


app_name = 'item'

urlpatterns = [
    path('', items, name='items'),
    path('<int:pk>/', ItemDetail.as_view(), name='detail'),
    path('new/', CreateItem.as_view(), name='new'),
    path('<int:pk>/delete/', delete_item, name='delete'),
    path('<int:pk>/edit/', EditItem.as_view(), name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.urls import path, include
from core.views import *
from item.views import *


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    # get rid of the last line
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

puddle/item/forms.py
from django import forms

from .models import Item


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')

puddle/item/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView

from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def items(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    query = request.GET.get('query', '')

    try:
        cat_id = int(request.GET.get('category', 0))
    except ValueError:
        cat_id = 0

    if cat_id:
        items = items.filter(category_id=cat_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'cat_id': cat_id,
    })


class ItemDetail(DetailView):
    model = Item
    template_name = 'item/detail.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        related_items = Item.objects.filter(category=self.object.category, is_sold=False).exclude(pk=self.object.pk)[0:3]
        context['related_items'] = related_items

        return context


class CreateItem(LoginRequiredMixin, CreateView):
    """Create a new item"""
    model = Item
    form_class = NewItemForm
    template_name = 'item/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'New item'
        return context

    def form_valid(self, form):
        item = form.save(commit=False)
        item.created_by = self.request.user
        item.save()
        return redirect('item:detail', pk=item.id)


class EditItem(LoginRequiredMixin, UpdateView):
    """Edit the item content"""
    model = Item
    form_class = EditItemForm
    template_name = 'item/form.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit item'
        return context

    def form_valid(self, form):
        self.object.save()
        return redirect('item:detail', pk=self.object.id)

    def get_queryset(self):  # returns a query only to a certain user
        queryset = super(EditItem, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user)
        return queryset


@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}
{{ item.name }}
{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-200 rounded-xl">
        <h1 class="mb-6 text-4xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>
        <br>

        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong>
            <br>
            {{ item.description }}
        </p>
        {% endif %}

        {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-gray-100 rounded-xl">
            <a href="{% url 'item:edit' item.id %}" class="inline-block px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit item</a>
            <a href="{% url 'item:delete' item.id %}" class="inline-block px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete item</a>
        </div>
        {% else %}
        <a href="{% url 'conversation:new' item.id %}"
           class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
            Contact seller
        </a>
        {% endif %}
    </div>
</div>

{% if related_items %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                        {% if item.image.url is not None %}
                        <div><img src="{{ item.image.url }}" class="rounded-t-xl"></div>
                        {% else %}
                        <div class="rounded-t-xl">No image</div>
                        {% endif %}
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

{% endblock %}

puddle/item/templates/item/form.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<div class="w-2/3 mx-auto p-5 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <div class="text-red-600 mt-5">{{ form.non_field_errors }}</div>
    <form class="mt-10" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="grid gap-6 mb-6 md-3">
            {% for f in form %}
            <div>
                <label class="block mb-2 text-lg font-semibold" for="{{ f.id_for_label }}">{{f.label}}</label>
                <div class="text-red-600 mb-5">{{ f.errors }}</div>
                {{ f|add_class:"border border-gray-300 text-gray-900 text-lg rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" }}
            </div>
            {% endfor %}
            <button type="submit" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Add item</button>
        </div>
    </form>
</div>
{% endblock %}

puddle/item/templates/item/items.html
{% extends 'core/base.html' %}
{% load cache %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="p-6 grid grid-cols-4 gap-4 bg-gray-100 rounded-xl">
        {% cache 30 sidebar %}
        <div class="col-span-1">
            <form action="{% url 'item:items' %}" method="get">
                <input class="w-full py-4 px-6 border rounded-xl" type="text" name="query" value="{{ query }}" placeholder="Find a bike, a chair or a car...">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% if not categories %}
                <p>No items</p>
                {% endif %}
                {% for cat in categories %}
                <li class="py-2 px-2 rounded-xl {% if cat.id == cat_id %}bg-gray-200{% endif %}">
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ cat.id }}">{{ cat.name }}</a>
                </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="font-semibold">Clear filters</p>
            <ul>
                <li>
                    <a href="{% url 'item:items' %}"
                       class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
                </li>
            </ul>
        </div>
        {% endcache %}
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% if not items %}
                <p>No items</p>
                {% endif %}
                {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        {% if item.image.url is not None %}
                        <div><img src="{{ item.image.url }}" class="rounded-t-xl"></div>
                        {% else %}
                        <div class="rounded-t-xl">No image</div>
                        {% endif %}
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}